const FETCH_CARS = 'FETCH_CARS';
const NEW_POST = 'NEW_POST';
const ADD = 'ADD';
const FETCH_POST_BYID = 'FETCH_POST_BYID';
const HIDE_HEADER = 'HIDE_HEADER';
const DATA_SEARCH = 'DATA_SEARCH';
const DATA_CHOICE = 'DATA_CHOICE';

export { 
  FETCH_CARS, NEW_POST ,ADD, FETCH_POST_BYID,
  HIDE_HEADER, DATA_SEARCH, DATA_CHOICE
};